apiVersion: v1
kind: Service
metadata:
  name: business-service
spec:
  selector:
    app: business-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001

---

apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db-service
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
