apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: bXlzZWNyZXQ=
  password: bXlzZWNyZXQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: business-service-secret
type: Opaque
data:
  secret_key: bXlzZWNyZXQ=
